### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by realthk** [amaximus/pollen_hu#9]
Pár napja tanúsítvány hibával nem tud kapcsolódni az oldalhoz:
```
2023-08-07 08:22:43.374 ERROR (MainThread) [homeassistant.components.sensor] pollen_hu: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/pollen_hu/sensor.py", line 123, in async_update
    self._pdata = await async_get_pdata(self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pollen_hu/sensor.py", line 48, in async_get_pdata
    async with self._session.get(url) as response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host efop180.antsz.hu:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]
```

pedig az érvényes:
![image](https://github.com/amaximus/pollen_hu/assets/5654575/f23da392-31e3-443e-bcdd-93d207049008)

**Comment by amaximus** [comment]
A [Home Assistant Hungary](https://www.facebook.com/groups/HomeAssistantHU/) FB csoportban már jelezte valaki és megírtam oda a megoldást.
Idemásolom"
```
Nos egy pillanatra ránéztem HA-ban a log pollen bejegyzéseire és az [https://efop180.antsz.hu/](https://efop180.antsz.hu/?fbclid=IwAR11wN0epFslAgPhz7DwMo8DWVKjxn8w8Q3L7CfiU-ysNVOvcjo7qvh-pEw) 
augusztus 2-án frissített TLS tanúsítványt ami a Netlock Trust EV CA 3 root tanúsítványt használja.
Ezt kell hozzáadni a gépen a CA store-hoz. Innen tölthető le: [https://netlock.hu/root-certificates/?lang=en](https://netlock.hu/root-certificates/?lang=en&fbclid=IwAR0MmehgcQFT3I1JhbSQ_E39GrEB_xKYMMDvD8_nEvU-RgeHF7s2CDxk-WY)
```

**Comment by tolnai** [comment]
Ha jól látom, hassos-es telepítés esetén nem valami egyszerű új cert-et hozzáadni a store-hoz. Hogy van ez hogy olyan a root ca amit egy (elvileg) friss distro nem ismer? Vagy majd jön ki új OS image aztán hátha abba belekerül?

**Comment by amaximus** [comment]
Bár továbbra is a CA store frissítése a NetLock root-intermediate tanúsítvánnyal az ajánlott, a most release-elt 0.5.0 verzió lehetővé teszi az SSL ellenörzés kikapcsolását.

Légy szíves frissítsd az integrációt és jelezz vissza.

**Comment by tolnai** [comment]
Köszi, így működik 👍, bár nyilván ez csak workaround...
![image](https://github.com/amaximus/pollen_hu/assets/29948020/dbbe79bc-7c9d-4f36-8f87-cbe6fe6ecaac)

**Comment by realthk** [comment]
Köszi, nekem is ez lett a megoldás (tartósan is: nem aggódom azon, h megtámadnák, átirányítanák a pollen.hu-t, hiszen max nem működik a lekérdezés, na bumm, nekünk nem tudnak más kárt okozni), HAOS-hez én sem találtam egyszerű és tartós módszert.
